#!/bin/sh

echo "🚀 Starting pre-commit checks..."

run_format_and_lint() {
    echo "📝 Formatting and linting staged files..."
    docker compose run -T --rm api sh -c "corepack yarn format:all"
    if [ $? -ne 0 ]; then
        echo "❌ Formatting or linting failed!"
        exit 1
    fi
}

run_tests() {
    echo "🧪 Running unit tests..."
    docker compose run -T --rm api sh -c "corepack yarn test --watchAll=false"
    if [ $? -ne 0 ]; then
        echo "❌ Tests failed!"
        exit 1
    fi
}

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | tr '\n' ' ')
if [ -z "$STAGED_FILES" ]; then
    echo "❌ No files staged for commit!"
    exit 1
fi

run_format_and_lint

echo "📦 Adding formatted files to the commit..."
git add $STAGED_FILES

run_tests

echo "✅ All pre-commit checks passed!"

exit 0